beans:
    prefix: beans-
    id_length: 4
    default_status: open
statuses:
    - name: open
      color: green
    - name: in-progress
      color: yellow
    - name: done
      color: gray
      archive: true
types:
    - name: task
      color: blue
    - name: feature
      color: green
    - name: bug
      color: red
    - name: epic
      color: purple
